### ISSUE TITLE
Customization of styles shouldn't base on publishing views/vendor files

### ISSUE THREAD

**Issue by brunoalfred** [protonemedia/laravel-splade#107]
I would recommend allowing developers to customize the components without publishing the views files. 
My opinions are inspired by this great article from folks [@filamentphp](https://filamentphp.com/blog/publishing-views-in-laravel).

PS: Emphasis could focus on enabling custom style without touching the vendor blade files.

**Comment by brunoalfred** [comment]
I tried to come up with custom head and body

```html

 <x-splade-table :for="$users" as="$user" class="min-w-full ">
                                <x-slot name="head">
                                    <thead class="bg-gray-50">
                                        <tr>
                                            <th scope="col"
                                                class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
                                                Name</th>
                                            <th scope="col"
                                                class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Title
                                            </th>
                                            <th scope="col"
                                                class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email
                                            </th>
                                            <th scope="col"
                                                class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Role
                                            </th>
                                            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                                                <span class="sr-only">Edit</span>
                                            </th>
                                        </tr>
                                    </thead>
                                </x-slot>

                                <x-slot name="body">
                                    <tbody class="divide-y divide-gray-200 bg-white">



                                        <tr>
                                            <td
                                                class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                                                Lindsay Walton</td>
                                            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">Front-end
                                                Developer</td>
                                            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                                                lindsay.walton@example.com</td>
                                            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">Member</td>
                                            <td
                                                class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                                                <a href="#" class="text-blue-600 hover:text-blue-900">Edit<span
                                                        class="sr-only">, Lindsay Walton</span></a>

                                            </td>
                                        </tr>


                                    </tbody>
                                </x-slot>
                            </x-splade-table>


``` 

Which appears as 
![Screenshot 2022-11-15 at 10 42 29](https://user-images.githubusercontent.com/55545250/201858925-e64c2810-5e0c-4123-991f-206a65581426.png)

How do i access the `$users` variable and loop on `tbody`. I have a dedicated table class `Tables/Users.php` with configurations.

**Comment by pascalbaljet** [comment]
The `as` attribute is meant for custom column cells, not for a full custom body. You may use the `resource` property of the `SpladeTable` to loop over the items:

```
<x-splade-table :for="$users">
    <x-slot name="head">
        <thead>
            <tr>
                <th>Email</th>
                <th>Name</th>
            </tr>
        </thead>
    </x-slot>

    <x-slot name="body">
        <tbody>
            @foreach($users->resource as $user)
                <tr>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->name }}</td>
                </tr>
            @endforeach
        </tbody>
    </x-slot>
</x-splade-table>
```

**Comment by brunoalfred** [comment]
In the controler ` 'users' => Users::class, ` where  `use App\Tables\Users;`, this leads to error: 
![Screenshot 2022-11-15 at 11 56 51](https://user-images.githubusercontent.com/55545250/201875090-c2d356a0-90e2-4aac-97c6-b1dbbbf62e8b.png)

**Comment by brunoalfred** [comment]
In the controler ` 'users' => Users::class, ` where  `use App\Tables\Users;`, this leads to error: 
![Screenshot 2022-11-15 at 11 56 51](https://user-images.githubusercontent.com/55545250/201875090-c2d356a0-90e2-4aac-97c6-b1dbbbf62e8b.png)

**Comment by pascalbaljet** [comment]
Ahh, got it. I'll add a helper method in a future release, but for now you may use this:

Instead of: 

```php
return view('table.custom', [
    'users' => Users::class
]);
```

Do this:

```php
return view('table.custom', [
    'users' => (new Users)->make(),
]);
```

**Comment by pascalbaljet** [comment]
In v0.7.4 you may also use `Users::build()`

**Comment by brunoalfred** [comment]
How do i hide and show columns in this scenario?

**Comment by brunoalfred** [comment]
![Screenshot 2022-11-16 at 14 22 32](https://user-images.githubusercontent.com/55545250/202167667-d9289344-71f5-4ffd-acb2-15b6cc08b376.png)

**Comment by MotionPhix** [comment]
To add on the customization issue, I have a menu that is a preloaded modal on mobile devices. Prior to the release of preloaded modals I customised the modal to be used as a menu except it wasn't working well since the files were linked to routes. But I customised it to position itself to the top of the screen instead of the middle (which is the default behaviour for modals). Now, to customise the position I had to publish the files and dig into the modal files and put a property that would change the alignment of the modal from **items-center** to **items-start**. It's really a small thing which could be provided by default to change the position, but now after upgrading, all those have had to be deleted, including my customisations. It's a pain to start publishing the files again and making the customisation every time there's an update. It could have been easier if you included an option to position the modal like we do with toasts.

**Comment by pascalbaljet** [comment]
We could add that feature, but when v1.0 hits, the templates stay mostly the same, so this wouldn't be a big problem. I'll always look for a balance between providing a fully featured, fully styled component and a more flexible component that you'll need to implement yourself. Mind that the current Splade components give you a massive head start.

For v1.0, I've split the components into functional and non-functional components (e.g., the data component is unstyled, and there is no need to publish it).

**Comment by MotionPhix** [comment]
Hello team, while still on the topic, I wanted to use the preloaded modal except that I wanted to make it align to the top of the screen, not the centre of the screen as in the video below:

https://user-images.githubusercontent.com/59722054/207032757-8643159c-cab7-40f2-8c39-d6e3485a619d.mp4

As you can see from the video, there's only one class that we could toggle to make the modal align either top, centre (default) or bottom of the screen. With the current situation, to access that class we are forced to publish the components. I wanted to ask if there's an easier way of getting around this, because putting a class on the **x-splade-modal** doesn't do anything. I am thinking putting an attribute on the **x-splade-modal** besides the **name** attribute (for preloaded modals) which we could probably name **placement** and then assign a position like *top*, *bottom* and if not provided then it will default to centre. What do you think?
