### ISSUE TITLE
How to avoid global component?

### ISSUE THREAD

**Issue by takielias** [protonemedia/laravel-splade#130]
From the docs, I learned that we have to register any custom component in the app.js file. So is there any way we can use different js functions/methods in a specific route/page, not in the global scope?

**Comment by pascalbaljet** [comment]
I'll add this to documentation, thanks for asking! Vue 3 supports [async components](https://vuejs.org/guide/components/async.html) with the `defineAsyncComponent` function.

In the main `app.js` file, you must import this function:

```js
import { createApp, defineAsyncComponent } from "vue/dist/vue.esm-bundler.js";
```

Then instead of importing the component directly, you may wrap the `import` call in the `defineAsyncComponent` callback.

```js
createApp({
    render: renderSpladeApp({ el }),
})
    .use(SpladePlugin, {
        "max_keep_alive": 10,
        "transform_anchors": false,
        "progress_bar": true,
    })
    .component("Counter", defineAsyncComponent(() => import("./Counter.vue")))
    .mount(el);
```

Now, the `Counter` component will only be loaded on pages/routes that actually use the component:

<img width="1070" alt="Schermafbeelding 2022-11-26 om 17 02 55" src="https://user-images.githubusercontent.com/8403149/204097855-b49bd36f-b70a-4844-a1ab-38e7fe2a943c.png">

**Comment by takielias** [comment]
@pascalbaljet Thanks for the quick solution. But It would be great If we can keep app.js file clean from defining any global definition unless it's required globally.

**Comment by pascalbaljet** [comment]
Why? How many custom components are you planning to create? Earlier versions of Laravel had [some boilerplate](https://github.com/laravel/laravel/blob/5.8/resources/js/app.js) to automatically register components:

```js
/**
 * The following block of code may be used to automatically register your
 * Vue components. It will recursively scan this directory for the Vue
 * components and automatically register them with their "basename".
 *
 * Eg. ./components/ExampleComponent.vue -> <example-component></example-component>
 */

const files = require.context('./', true, /\.vue$/i);
files.keys().map(key => Vue.component(key.split('/').pop().split('.')[0], files(key).default));
```

Anyhow, what's the real problem? Because with the async components, the browser won't load the components unless needed.

**Comment by pascalbaljet** [comment]
I've added this to the docs: https://splade.dev/docs/custom-vue-components

**Comment by takielias** [comment]
@pascalbaljet Thanks a lot for the support.
