### ISSUE TITLE
How can I Render only the HTML of a view without the splade scaffolding?

### ISSUE THREAD

**Issue by LordMcAwesome** [protonemedia/laravel-splade#175]
Via AJAX I run a GET request with search and filter parameters, so that the backend returns a view.
After the request returned to the frontend, I place that view's data into a specific DOM element:

```
...
let url = "/overview/get-offers-and-invoices/" + search_term + "/" + filter1 + "/" + filter2;
$.ajax({
    type: "GET",
    url: url,
    success: function (data) {
        $('#overview-offers-and-invoices-main-div').html(data);
    }
});
```

If I do that, the splade scaffolding is being applied to that view rendering a whole HTML page inside my HTML page.
I only wish to render the HTML of the view/blade file.

My "workaround" is to place the route outside of:
```
Route::middleware(['splade'])->group(function () {
   ...
});
### PLACE IT HERE###
```

But then I of course lose the Splade benefits like the Link components functionality.

**Comment by pascalbaljet** [comment]
It's correct to exclude the route from the Splade middleware, and that's not really the problem. Alternatively, you could send a `X-Splade-Skip-Middleware` header:

```js
$.ajax({
  headers: {
    'X-Splade-Skip-Middleware': true
  }
});
```

Or you could use the `skipSpladeMiddleware` method on a `Response` instance:

```php
return response()->view('template')->skipSpladeMiddleware();
```

Both are relatively new and only used internally, so they still need to be documented. However, the real problem is this piece of code:

```js
$('#overview-offers-and-invoices-main-div').html(data);
```

This will not mount Vue components (like the Link component) as you're updating the DOM with jQuery and not with Vue. On top of my head, you should write a [custom Vue component](https://splade.dev/docs/custom-vue-components) that performs the request, and then uses the `SpladeRender` component to mount the HTML:

```vue
<template>
    <SpladeRender :html="html" />
</template>

<script setup>
import { onMounted, ref } from "vue";

const html = ref();

onMounted(() => {
    fetch(url).then(html.value => response.text())
});
</script>
```

I don't know about your design decisions, but there might be better ways to achieve your goal. Either way, I'll consider a dedicated Splade component for loading views. Also, check out the [Defer component](https://splade.dev/docs/x-defer). This component can perform the request and then you only have to mount it.

**Comment by LordMcAwesome** [comment]
Oh that worked perfectly!

In my controller I changed the return statement from
```
return view('components.overview-items', $data);
```
to
```
return response()->view('components.overview-items', $data)->skipSpladeMiddleware();
```

Then, I changed the ajax call's success method from
```
$('#overview-offers-and-invoices-table-main-div').html(data);
```
to
```
html.value = data
```

And as you said, I added the output to the Template tags of the component:
```
<template>
    <SpladeRender :html="html"/>
</template>
```

Thank you very much for your help!
And of course for Splade 😊
