### ISSUE TITLE
[Question] Catch API result in splade component form dynamically ? 

### ISSUE THREAD

**Issue by olimolly** [protonemedia/laravel-splade#432]
I have a specific situation in which I would like to filter dynamically the result of an API request using a splade form to fill parameters. 

The blocking point I am facing stands once I submit the request. How can I catch the result in order to manipulate the returned json like I would be able to do in a Vue component ? I think there must be a way to do so since the validation method is called without refreshing the page. Would the solution be related to x-rehydrate or event-bus ?

Thanks in advance,

**Comment by Adel-Kazem** [comment]
As I understood your issue is that you want to use an input form to send it into the back end of the app and process it and then return the result of that processed input, am I right? I don't know if this might help you I'm mentioning the [defer component](https://splade.dev/docs/x-defer#watch), take a look at it and decide if might help you..

**Comment by pascalbaljet** [comment]
> I have a specific situation in which I would like to filter dynamically the result of an API request using a splade form to fill parameters.
> 
> The blocking point I am facing stands once I submit the request. How can I catch the result in order to manipulate the returned json like I would be able to do in a Vue component ? I think there must be a way to do so since the validation method is called without refreshing the page. Would the solution be related to x-rehydrate or event-bus ?
> 
> Thanks in advance,

I have no idea what you're trying to build. Can you come up with a code example?
