### ISSUE TITLE
Page reloads with Link -> Modal form

### ISSUE THREAD

**Issue by stescacom** [protonemedia/laravel-splade#468]
I have a page with Link to a form that shows in Modal. When I click the link the whole page is reloaded the first time it shows then for the second time it doesn't happen.

I am using Laravel 10.x. What could be the issue?

`<x-card.card-link modal href="{{ route('...') }}" preserve-scroll>Open Create Form</x-card.card-link>`

In the form page:

`<x-layouts.user-layout>
    <x-splade-modal>
        ...
    </x-splade-modal>
</x-layouts.user-layout>`

The same pattern is repeated if I have two separate sections on the page, each of the section has its own controller and a different route. If I post the form of one controller and then open the second section create form the page reloads completely.

from the first controller `store` method I am returning response with `return back();`

**Comment by mbeckerle-xqueue** [comment]
Can you please test if the same happens if you build your project and not use Vite's hot replacement?
I think it is an issue with Vite. I experienced the same problem but after some `npm run build` it seems to behave as expected. 

If I am in dev mode I experience the following:

1. I load the page and navigate to some link, which opens a modal
2. I open modal and it shows up. At same time full page refresh is started.
3. Page fully refreshes, I navigate again to that link
4. I open Modal and everything is fine.
5. I change a VUE component and it is hot replaced and everything works as expected
6. I change Splade component and the whole page is refreshed as it is actually some Blade thing and needs full reload
7. Now I am in point 1 again and the whole modal problem starts again

Just as a side note: I added the modal tag around the layout and not inside but I am not sure if that has any influence at all...
