### ISSUE TITLE
When will be laravel-Splade v2 released

### ISSUE THREAD

**Issue by dhsont** [protonemedia/laravel-splade#537]
I wanted to start new project but waiting for   laravel-Splade v2 to be released.

Looks no progress from last 2 months.

May i know when i will be released ?

**Comment by greaterking** [comment]
Happy New Year! I'm curious to know as well...should we still be banking on Splade2?

**Comment by Adel-Kazem** [comment]
I am also interested to know when the next release? @pascalbaljet

**Comment by KimGrimm** [comment]
I am highly interested in new stuff from @pascalbaljet too. Splade is really awesome and has big potential

**Comment by pascalbaljet** [comment]
Hey everybody! I just wanted to let you know that I'm currently investigating the future direction of Splade. Since I [posted it on Twitter](https://twitter.com/pascalbaljet/status/1759351165446242315), I thought it would be nice to share it here as well. I've been quiet in this repo but have worked hard on version 2 (built upon Splade Core).

Both Splade Core and Splade v2 should have been released months ago. It's an incredibly complicated yet exciting project. It's way better than v2 in most cases, but maybe I've taken the idea too far. I feel like I'm on the wrong path and in an endless loop of fixing things before I can make any real progress. Every time a real showstopper pops up, and I find a solution, another one presents itself. Of course, this is always the case with building software, but Splade Core is such a beast that this leads to very slow progress. Usually, I would release it and fix things along the way, as I did with Splade v1, but if the fundamentals are not working correctly, it won't make sense.

I understand if you have doubts about starting new projects with Splade, but there's little I can do about it now. My time is limited, and I make practically no money from Splade, so I must avoid tunnel vision at all costs.

**Comment by KimGrimm** [comment]
> Hey everybody! I just wanted to let you know that I'm currently investigating the future direction of Splade. Since I [posted it on Twitter](https://twitter.com/pascalbaljet/status/1759351165446242315), I thought it would be nice to share it here as well. I've been quiet in this repo but have worked hard on version 2 (built upon Splade Core).
> 
> Both Splade Core and Splade v2 should have been released months ago. It's an incredibly complicated yet exciting project. It's way better than v1 in most cases, but maybe I've taken the idea too far. I feel like I'm on the wrong path and in an endless loop of fixing things before I can make any real progress. Every time a real showstopper pops up, and I find a solution, another one presents itself. Of course, this is always the case with building software, but Splade Core is such a beast that this leads to very slow progress. Usually, I would release it and fix things along the way, as I did with Splade v1, but if the fundamentals are not working correctly, it won't make sense.
> 
> I understand if you have doubts about starting new projects with Splade, but there's little I can do about it now. My time is limited, and I make practically no money from Splade, so I must avoid tunnel vision at all costs.

Hey Pascal! Thanks for the honest update. I feel you brother. Being involved in massive things is always hard as a sidehustle.
I hope you find time to do what's needed in your pace and with the style you've got!

**Comment by thecyrilcril** [comment]
> Hey everybody! I just wanted to let you know that I'm currently investigating the future direction of Splade. Since I [posted it on Twitter](https://twitter.com/pascalbaljet/status/1759351165446242315), I thought it would be nice to share it here as well. I've been quiet in this repo but have worked hard on version 2 (built upon Splade Core).
> 
> Both Splade Core and Splade v2 should have been released months ago. It's an incredibly complicated yet exciting project. It's way better than v1 in most cases, but maybe I've taken the idea too far. I feel like I'm on the wrong path and in an endless loop of fixing things before I can make any real progress. Every time a real showstopper pops up, and I find a solution, another one presents itself. Of course, this is always the case with building software, but Splade Core is such a beast that this leads to very slow progress. Usually, I would release it and fix things along the way, as I did with Splade v1, but if the fundamentals are not working correctly, it won't make sense.
> 
> I understand if you have doubts about starting new projects with Splade, but there's little I can do about it now. My time is limited, and I make practically no money from Splade, so I must avoid tunnel vision at all costs.

Thank you @pascalbaljet for Splade and your transparency about the situation. I took a chance on the project and have been building the biggest project of my career yet with it. I have hit a hard wall several times even today I considered restarting the project in livewire.
We are with you and we trust your wits... take your time, be brave!!
